# Generated by Django 3.1.7 on 2021-02-27 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarZone2', '0003_auto_20210227_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 27, 20, 49, 5, 703403)),
        ),
    ]
