# Generated by Django 3.1.7 on 2021-02-27 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarZone2', '0004_auto_20210227_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 27, 23, 1, 22, 147149)),
        ),
    ]
